name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc-9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up CMake and gtest
      run: |
        sudo apt-get -y install cmake libgtest-dev
    - name: Build library and tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run tests
      run: |
        ./test/mylibrary_test

